

[[edges]]
scope = "Global"
from = "laiu1_enum_parameterized__literal"
to = ["laiu1_lambda"]


[[edges]]
scope = "Global"
from = "laiu1_lambda"
to = ["laiu1_infix_expression"]

[[edges]]
scope = "Global"
from = "t7czz_enum_parameterized__literal"
to = ["t7czz_lambda"]


[[edges]]
scope = "Global"
from = "t7czz_lambda"
to = ["t7czz_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "gqg0l_enum_parameterized__literal"
to = ["gqg0l_lambda"]


[[edges]]
scope = "Global"
from = "gqg0l_lambda"
to = ["gqg0l_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "mj7yz_enum_parameterized__literal"
to = ["mj7yz_lambda"]

[[edges]]
scope = "Global"
from = "zk98i_enum_parameterized__literal"
to = ["zk98i_infix_expression"]

[[edges]]
scope = "Global"
from = "acjjd_enum_parameterized__literal"
to = ["acjjd_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "yor41_enum_parameterized__literal"
to = ["yor41_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "dahox_enum_parameterized__literal"
to = ["dahox_variable"]


[[edges]]
scope = "Global"
from = "dahox_variable"
to = ["dahox_infix_expression"]

[[edges]]
scope = "Global"
from = "eboe6_enum_parameterized__literal"
to = ["eboe6_variable"]


[[edges]]
scope = "Global"
from = "eboe6_variable"
to = ["eboe6_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "fdsu0_enum_parameterized__literal"
to = ["fdsu0_variable"]


[[edges]]
scope = "Global"
from = "fdsu0_variable"
to = ["fdsu0_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "eh7hu_enum_parameterized__literal"
to = ["eh7hu_variable"]

[[edges]]
scope = "Global"
from = "tur9h_enum_parameterized__literal"
to = ["tur9h_import"]

[[edges]]
scope = "Global"
from = "cvv1q_enum_parameterized__literal"
to = ["cvv1q_enum_parameterized__literal"]

[[edges]]
scope = "Global"
from = "wdla5_property__literal"
to = ["wdla5_lambda"]


[[edges]]
scope = "Global"
from = "wdla5_lambda"
to = ["wdla5_infix_expression"]

[[edges]]
scope = "Global"
from = "x7cuh_property__literal"
to = ["x7cuh_lambda"]


[[edges]]
scope = "Global"
from = "x7cuh_lambda"
to = ["x7cuh_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "o6qdl_property__literal"
to = ["o6qdl_lambda"]


[[edges]]
scope = "Global"
from = "o6qdl_lambda"
to = ["o6qdl_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "ju10c_property__literal"
to = ["ju10c_lambda"]

[[edges]]
scope = "Global"
from = "yefcz_property__literal"
to = ["yefcz_infix_expression"]

[[edges]]
scope = "Global"
from = "xqzd6_property__literal"
to = ["xqzd6_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "jgqtd_property__literal"
to = ["jgqtd_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "q20ky_property__literal"
to = ["q20ky_property__literal"]

[[edges]]
scope = "Global"
from = "ucrbi_lambda__literal"
to = ["ucrbi_infix_expression"]

[[edges]]
scope = "Global"
from = "c7xme_lambda__literal"
to = ["c7xme_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "rmv4d_lambda__literal"
to = ["rmv4d_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "niosy_lambda__literal"
to = ["niosy_lambda__literal"]

[[edges]]
scope = "Global"
from = "mj7ju_sealed_class_parameterized__literal"
to = ["mj7ju_lambda"]


[[edges]]
scope = "Global"
from = "mj7ju_lambda"
to = ["mj7ju_infix_expression"]

[[edges]]
scope = "Global"
from = "wlxut_sealed_class_parameterized__literal"
to = ["wlxut_lambda"]


[[edges]]
scope = "Global"
from = "wlxut_lambda"
to = ["wlxut_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "f4mru_sealed_class_parameterized__literal"
to = ["f4mru_lambda"]


[[edges]]
scope = "Global"
from = "f4mru_lambda"
to = ["f4mru_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "sl1yf_sealed_class_parameterized__literal"
to = ["sl1yf_lambda"]

[[edges]]
scope = "Global"
from = "nkb63_sealed_class_parameterized__literal"
to = ["nkb63_infix_expression"]

[[edges]]
scope = "Global"
from = "we7ad_sealed_class_parameterized__literal"
to = ["we7ad_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "xxqsf_sealed_class_parameterized__literal"
to = ["xxqsf_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "t3zdf_sealed_class_parameterized__literal"
to = ["t3zdf_import"]

[[edges]]
scope = "Global"
from = "cqvz2_sealed_class_parameterized__literal"
to = ["cqvz2_sealed_class_parameterized__literal"]

[[edges]]
scope = "Global"
from = "tseln_expression_invocation_positive__literal"
to = ["tseln_expression_invocation_positive__literal"]

[[edges]]
scope = "Global"
from = "ge6ly_expression_invocation_negative__literal"
to = ["ge6ly_expression_invocation_negative__literal"]

[[edges]]
scope = "Global"
from = "i1hms_variable__literal"
to = ["i1hms_infix_expression"]

[[edges]]
scope = "Global"
from = "f5cwb_variable__literal"
to = ["f5cwb_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "oxhyc_variable__literal"
to = ["oxhyc_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "fnbud_variable__literal"
to = ["fnbud_variable__literal"]

[[edges]]
scope = "Global"
from = "velr0_enum"
to = ["velr0_enum_parameterized"]


[[edges]]
scope = "Global"
from = "velr0_enum_parameterized"
to = ["velr0_lambda"]


[[edges]]
scope = "Global"
from = "velr0_lambda"
to = ["velr0_infix_expression"]

[[edges]]
scope = "Global"
from = "jr4er_enum"
to = ["jr4er_enum_parameterized"]


[[edges]]
scope = "Global"
from = "jr4er_enum_parameterized"
to = ["jr4er_lambda"]


[[edges]]
scope = "Global"
from = "jr4er_lambda"
to = ["jr4er_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "oofya_enum"
to = ["oofya_enum_parameterized"]


[[edges]]
scope = "Global"
from = "oofya_enum_parameterized"
to = ["oofya_lambda"]


[[edges]]
scope = "Global"
from = "oofya_lambda"
to = ["oofya_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "p09ui_enum"
to = ["p09ui_enum_parameterized"]


[[edges]]
scope = "Global"
from = "p09ui_enum_parameterized"
to = ["p09ui_lambda"]

[[edges]]
scope = "Global"
from = "fb1re_enum"
to = ["fb1re_enum_parameterized"]


[[edges]]
scope = "Global"
from = "fb1re_enum_parameterized"
to = ["fb1re_infix_expression"]

[[edges]]
scope = "Global"
from = "ax6v5_enum"
to = ["ax6v5_enum_parameterized"]


[[edges]]
scope = "Global"
from = "ax6v5_enum_parameterized"
to = ["ax6v5_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "d0e5s_enum"
to = ["d0e5s_enum_parameterized"]


[[edges]]
scope = "Global"
from = "d0e5s_enum_parameterized"
to = ["d0e5s_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "v5gea_enum"
to = ["v5gea_enum_parameterized"]


[[edges]]
scope = "Global"
from = "v5gea_enum_parameterized"
to = ["v5gea_variable"]


[[edges]]
scope = "Global"
from = "v5gea_variable"
to = ["v5gea_infix_expression"]

[[edges]]
scope = "Global"
from = "dkzk9_enum"
to = ["dkzk9_enum_parameterized"]


[[edges]]
scope = "Global"
from = "dkzk9_enum_parameterized"
to = ["dkzk9_variable"]


[[edges]]
scope = "Global"
from = "dkzk9_variable"
to = ["dkzk9_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "y1ca9_enum"
to = ["y1ca9_enum_parameterized"]


[[edges]]
scope = "Global"
from = "y1ca9_enum_parameterized"
to = ["y1ca9_variable"]


[[edges]]
scope = "Global"
from = "y1ca9_variable"
to = ["y1ca9_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "wygnb_enum"
to = ["wygnb_enum_parameterized"]


[[edges]]
scope = "Global"
from = "wygnb_enum_parameterized"
to = ["wygnb_variable"]

[[edges]]
scope = "Global"
from = "k4mqz_enum"
to = ["k4mqz_enum_parameterized"]


[[edges]]
scope = "Global"
from = "k4mqz_enum_parameterized"
to = ["k4mqz_import"]

[[edges]]
scope = "Global"
from = "dxils_enum"
to = ["dxils_enum_parameterized"]

[[edges]]
scope = "Global"
from = "tcjqy_enum"
to = ["tcjqy_infix_expression"]

[[edges]]
scope = "Global"
from = "cmiza_enum"
to = ["cmiza_lambda"]


[[edges]]
scope = "Global"
from = "cmiza_lambda"
to = ["cmiza_infix_expression"]

[[edges]]
scope = "Global"
from = "p9zh8_enum"
to = ["p9zh8_lambda"]


[[edges]]
scope = "Global"
from = "p9zh8_lambda"
to = ["p9zh8_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "qcr5o_enum"
to = ["qcr5o_lambda"]


[[edges]]
scope = "Global"
from = "qcr5o_lambda"
to = ["qcr5o_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "sojex_enum"
to = ["sojex_lambda"]

[[edges]]
scope = "Global"
from = "tmhih_enum"
to = ["tmhih_variable"]


[[edges]]
scope = "Global"
from = "tmhih_variable"
to = ["tmhih_infix_expression"]

[[edges]]
scope = "Global"
from = "fueka_enum"
to = ["fueka_variable"]


[[edges]]
scope = "Global"
from = "fueka_variable"
to = ["fueka_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "jkbm6_enum"
to = ["jkbm6_variable"]


[[edges]]
scope = "Global"
from = "jkbm6_variable"
to = ["jkbm6_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "f7cnc_enum"
to = ["f7cnc_variable"]

[[edges]]
scope = "Global"
from = "dgmkx_enum"
to = ["dgmkx_import"]

[[edges]]
scope = "Global"
from = "vulae_enum"
to = ["vulae_enum"]

[[edges]]
scope = "Global"
from = "szrh2_sealed_class"
to = ["szrh2_lambda"]


[[edges]]
scope = "Global"
from = "szrh2_lambda"
to = ["szrh2_infix_expression"]

[[edges]]
scope = "Global"
from = "xsh9e_sealed_class"
to = ["xsh9e_lambda"]


[[edges]]
scope = "Global"
from = "xsh9e_lambda"
to = ["xsh9e_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "wx0ns_sealed_class"
to = ["wx0ns_lambda"]


[[edges]]
scope = "Global"
from = "wx0ns_lambda"
to = ["wx0ns_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "o0dnu_sealed_class"
to = ["o0dnu_lambda"]

[[edges]]
scope = "Global"
from = "xuhrh_sealed_class"
to = ["xuhrh_variable"]


[[edges]]
scope = "Global"
from = "xuhrh_variable"
to = ["xuhrh_infix_expression"]

[[edges]]
scope = "Global"
from = "nutjb_sealed_class"
to = ["nutjb_variable"]


[[edges]]
scope = "Global"
from = "nutjb_variable"
to = ["nutjb_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "tvnhd_sealed_class"
to = ["tvnhd_variable"]


[[edges]]
scope = "Global"
from = "tvnhd_variable"
to = ["tvnhd_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "dz4vb_sealed_class"
to = ["dz4vb_variable"]

[[edges]]
scope = "Global"
from = "mc8ur_sealed_class"
to = ["mc8ur_infix_expression"]

[[edges]]
scope = "Global"
from = "obaih_sealed_class"
to = ["obaih_import"]

[[edges]]
scope = "Global"
from = "twr4s_sealed_class"
to = ["twr4s_sealed_class"]
