[[edges]]
scope = "Global"
from = "ytgst_enum_parameterized__literal"
to = ["ytgst_lambda"]


[[edges]]
scope = "Global"
from = "ytgst_lambda"
to = ["ytgst_infix_expression"]

[[edges]]
scope = "Global"
from = "goloi_enum_parameterized__literal"
to = ["goloi_lambda"]


[[edges]]
scope = "Global"
from = "goloi_lambda"
to = ["goloi_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "fiwqt_enum_parameterized__literal"
to = ["fiwqt_lambda"]


[[edges]]
scope = "Global"
from = "fiwqt_lambda"
to = ["fiwqt_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "vxpuq_enum_parameterized__literal"
to = ["vxpuq_lambda"]

[[edges]]
scope = "Global"
from = "idbhc_enum_parameterized__literal"
to = ["idbhc_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "id8fl_enum_parameterized__literal"
to = ["id8fl_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "jxxay_enum_parameterized__literal"
to = ["jxxay_variable"]


[[edges]]
scope = "Global"
from = "jxxay_variable"
to = ["jxxay_infix_expression"]

[[edges]]
scope = "Global"
from = "cbyjw_enum_parameterized__literal"
to = ["cbyjw_variable"]


[[edges]]
scope = "Global"
from = "cbyjw_variable"
to = ["cbyjw_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "xnjf2_enum_parameterized__literal"
to = ["xnjf2_variable"]


[[edges]]
scope = "Global"
from = "xnjf2_variable"
to = ["xnjf2_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "dxums_enum_parameterized__literal"
to = ["dxums_variable"]

[[edges]]
scope = "Global"
from = "aukkj_enum_parameterized__literal"
to = ["aukkj_import"]

[[edges]]
scope = "Global"
from = "ayhas_enum_parameterized__literal"
to = ["ayhas_infix_expression"]

[[edges]]
scope = "Global"
from = "kl9ry_enum_parameterized__literal"
to = ["kl9ry_enum_parameterized__literal"]

[[edges]]
scope = "Global"
from = "tnd41_property__literal"
to = ["tnd41_lambda"]


[[edges]]
scope = "Global"
from = "tnd41_lambda"
to = ["tnd41_infix_expression"]

[[edges]]
scope = "Global"
from = "jt85p_property__literal"
to = ["jt85p_lambda"]


[[edges]]
scope = "Global"
from = "jt85p_lambda"
to = ["jt85p_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "xb9an_property__literal"
to = ["xb9an_lambda"]


[[edges]]
scope = "Global"
from = "xb9an_lambda"
to = ["xb9an_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "a6b04_property__literal"
to = ["a6b04_lambda"]

[[edges]]
scope = "Global"
from = "yh4sl_property__literal"
to = ["yh4sl_infix_expression"]

[[edges]]
scope = "Global"
from = "qoxv6_property__literal"
to = ["qoxv6_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "bbhvv_property__literal"
to = ["bbhvv_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "ts6ki_property__literal"
to = ["ts6ki_property__literal"]

[[edges]]
scope = "Global"
from = "nxkgk_lambda__literal"
to = ["nxkgk_infix_expression"]

[[edges]]
scope = "Global"
from = "eclq7_lambda__literal"
to = ["eclq7_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "qgdl5_lambda__literal"
to = ["qgdl5_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "wqw50_lambda__literal"
to = ["wqw50_lambda__literal"]

[[edges]]
scope = "Global"
from = "tudra_sealed_class_parameterized__literal"
to = ["tudra_lambda"]


[[edges]]
scope = "Global"
from = "tudra_lambda"
to = ["tudra_infix_expression"]

[[edges]]
scope = "Global"
from = "uzk6d_sealed_class_parameterized__literal"
to = ["uzk6d_lambda"]


[[edges]]
scope = "Global"
from = "uzk6d_lambda"
to = ["uzk6d_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "b9lej_sealed_class_parameterized__literal"
to = ["b9lej_lambda"]


[[edges]]
scope = "Global"
from = "b9lej_lambda"
to = ["b9lej_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "ldke9_sealed_class_parameterized__literal"
to = ["ldke9_lambda"]

[[edges]]
scope = "Global"
from = "t6qqj_sealed_class_parameterized__literal"
to = ["t6qqj_infix_expression"]

[[edges]]
scope = "Global"
from = "kltcv_sealed_class_parameterized__literal"
to = ["kltcv_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "riscq_sealed_class_parameterized__literal"
to = ["riscq_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "ylcny_sealed_class_parameterized__literal"
to = ["ylcny_import"]

[[edges]]
scope = "Global"
from = "cni9y_sealed_class_parameterized__literal"
to = ["cni9y_sealed_class_parameterized__literal"]

[[edges]]
scope = "Global"
from = "cyti8_expression_invocation_positive__literal"
to = ["cyti8_expression_invocation_positive__literal"]

[[edges]]
scope = "Global"
from = "w065l_expression_invocation_negative__literal"
to = ["w065l_expression_invocation_negative__literal"]

[[edges]]
scope = "Global"
from = "foryu_variable__literal"
to = ["foryu_infix_expression"]

[[edges]]
scope = "Global"
from = "nqpeg_variable__literal"
to = ["nqpeg_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "b0stt_variable__literal"
to = ["b0stt_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "jvuat_variable__literal"
to = ["jvuat_variable__literal"]

[[edges]]
scope = "Global"
from = "kirbn_enum"
to = ["kirbn_enum_parameterized"]


[[edges]]
scope = "Global"
from = "kirbn_enum_parameterized"
to = ["kirbn_lambda"]


[[edges]]
scope = "Global"
from = "kirbn_lambda"
to = ["kirbn_infix_expression"]

[[edges]]
scope = "Global"
from = "l4kub_enum"
to = ["l4kub_enum_parameterized"]


[[edges]]
scope = "Global"
from = "l4kub_enum_parameterized"
to = ["l4kub_lambda"]


[[edges]]
scope = "Global"
from = "l4kub_lambda"
to = ["l4kub_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "ua5us_enum"
to = ["ua5us_enum_parameterized"]


[[edges]]
scope = "Global"
from = "ua5us_enum_parameterized"
to = ["ua5us_lambda"]


[[edges]]
scope = "Global"
from = "ua5us_lambda"
to = ["ua5us_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "asn0d_enum"
to = ["asn0d_enum_parameterized"]


[[edges]]
scope = "Global"
from = "asn0d_enum_parameterized"
to = ["asn0d_lambda"]

[[edges]]
scope = "Global"
from = "cvjbu_enum"
to = ["cvjbu_enum_parameterized"]


[[edges]]
scope = "Global"
from = "cvjbu_enum_parameterized"
to = ["cvjbu_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "k9o4w_enum"
to = ["k9o4w_enum_parameterized"]


[[edges]]
scope = "Global"
from = "k9o4w_enum_parameterized"
to = ["k9o4w_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "swued_enum"
to = ["swued_enum_parameterized"]


[[edges]]
scope = "Global"
from = "swued_enum_parameterized"
to = ["swued_variable"]


[[edges]]
scope = "Global"
from = "swued_variable"
to = ["swued_infix_expression"]

[[edges]]
scope = "Global"
from = "ddcjn_enum"
to = ["ddcjn_enum_parameterized"]


[[edges]]
scope = "Global"
from = "ddcjn_enum_parameterized"
to = ["ddcjn_variable"]


[[edges]]
scope = "Global"
from = "ddcjn_variable"
to = ["ddcjn_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "rpqaz_enum"
to = ["rpqaz_enum_parameterized"]


[[edges]]
scope = "Global"
from = "rpqaz_enum_parameterized"
to = ["rpqaz_variable"]


[[edges]]
scope = "Global"
from = "rpqaz_variable"
to = ["rpqaz_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "yr4vd_enum"
to = ["yr4vd_enum_parameterized"]


[[edges]]
scope = "Global"
from = "yr4vd_enum_parameterized"
to = ["yr4vd_variable"]

[[edges]]
scope = "Global"
from = "thadc_enum"
to = ["thadc_enum_parameterized"]


[[edges]]
scope = "Global"
from = "thadc_enum_parameterized"
to = ["thadc_import"]

[[edges]]
scope = "Global"
from = "o3dw4_enum"
to = ["o3dw4_enum_parameterized"]


[[edges]]
scope = "Global"
from = "o3dw4_enum_parameterized"
to = ["o3dw4_infix_expression"]

[[edges]]
scope = "Global"
from = "mgcmb_enum"
to = ["mgcmb_enum_parameterized"]

[[edges]]
scope = "Global"
from = "sd0yk_enum"
to = ["sd0yk_lambda"]


[[edges]]
scope = "Global"
from = "sd0yk_lambda"
to = ["sd0yk_infix_expression"]

[[edges]]
scope = "Global"
from = "y6adq_enum"
to = ["y6adq_lambda"]


[[edges]]
scope = "Global"
from = "y6adq_lambda"
to = ["y6adq_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "ppd8l_enum"
to = ["ppd8l_lambda"]


[[edges]]
scope = "Global"
from = "ppd8l_lambda"
to = ["ppd8l_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "w6ppe_enum"
to = ["w6ppe_lambda"]

[[edges]]
scope = "Global"
from = "ws7ht_enum"
to = ["ws7ht_variable"]


[[edges]]
scope = "Global"
from = "ws7ht_variable"
to = ["ws7ht_infix_expression"]

[[edges]]
scope = "Global"
from = "x1h5f_enum"
to = ["x1h5f_variable"]


[[edges]]
scope = "Global"
from = "x1h5f_variable"
to = ["x1h5f_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "l9kgz_enum"
to = ["l9kgz_variable"]


[[edges]]
scope = "Global"
from = "l9kgz_variable"
to = ["l9kgz_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "jm6kk_enum"
to = ["jm6kk_variable"]

[[edges]]
scope = "Global"
from = "zxcgr_enum"
to = ["zxcgr_infix_expression"]

[[edges]]
scope = "Global"
from = "ozvwy_enum"
to = ["ozvwy_import"]

[[edges]]
scope = "Global"
from = "rimqp_enum"
to = ["rimqp_enum"]

[[edges]]
scope = "Global"
from = "xc57b_sealed_class"
to = ["xc57b_lambda"]


[[edges]]
scope = "Global"
from = "xc57b_lambda"
to = ["xc57b_infix_expression"]

[[edges]]
scope = "Global"
from = "kmezr_sealed_class"
to = ["kmezr_lambda"]


[[edges]]
scope = "Global"
from = "kmezr_lambda"
to = ["kmezr_lambda_invocation_positive"]

[[edges]]
scope = "Global"
from = "azqrl_sealed_class"
to = ["azqrl_lambda"]


[[edges]]
scope = "Global"
from = "azqrl_lambda"
to = ["azqrl_lambda_invocation_negative"]

[[edges]]
scope = "Global"
from = "zwucn_sealed_class"
to = ["zwucn_lambda"]

[[edges]]
scope = "Global"
from = "dw13u_sealed_class"
to = ["dw13u_variable"]


[[edges]]
scope = "Global"
from = "dw13u_variable"
to = ["dw13u_infix_expression"]

[[edges]]
scope = "Global"
from = "up63u_sealed_class"
to = ["up63u_variable"]


[[edges]]
scope = "Global"
from = "up63u_variable"
to = ["up63u_expression_invocation_positive"]

[[edges]]
scope = "Global"
from = "iztpd_sealed_class"
to = ["iztpd_variable"]


[[edges]]
scope = "Global"
from = "iztpd_variable"
to = ["iztpd_expression_invocation_negative"]

[[edges]]
scope = "Global"
from = "klqrb_sealed_class"
to = ["klqrb_variable"]

[[edges]]
scope = "Global"
from = "rmjvf_sealed_class"
to = ["rmjvf_infix_expression"]

[[edges]]
scope = "Global"
from = "tsrr1_sealed_class"
to = ["tsrr1_import"]

[[edges]]
scope = "Global"
from = "yeltr_sealed_class"
to = ["yeltr_sealed_class"]
